### ISSUE TITLE
Could not open download link, could you please upload them on Google Drive?

### ISSUE THREAD

**Issue by icmpnorequest** [LibrariesHacked/openlibrary-search#11]
Hi,

The provided link to download the datasets is invalid. I was wondering could you please upload them on Google Drive for usage? Thanks in advance.

**Comment by pierow2k** [comment]
@icmpnorequest - Links to the data dumps are available on Open Library's *Data Dumps* page at:

* [https://openlibrary.org/developers/dumps](https://openlibrary.org/developers/dumps)

**Comment by DaveBathnes** [comment]
Sorry for the very late reply to this. It doesn't quite fall into the scope of this project, but I did think that there might be situations in which the original links are invalid, and I'd like to do anything I can to help that.

Will follow up shortly.

**Comment by icmpnorequest** [comment]
Thank you for your comments and I will close this issue.
